dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="validsdp"
  - COQEAL_URL="https://github.com/CoqEAL/CoqEAL.git"
  - COQEAL_VERSION="1993703c194043b0c5e3f1c1877f4b58f3b7b266"
  matrix:
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.9"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    : Updating OPAM cache
    opam update -y
    : Installing OPAM deps
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    opam pin add -n -y -k path coq-libvalidsdp .
    opam pin add -n -y -k path coq-validsdp .
    opam remove -y coq-mathcomp-character  # Check coq-mathcomp-field is enough
    opam install -y -v -j ${NJOBS} coq-libvalidsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-libvalidsdp

script:
- echo -e "${ANSI_YELLOW}Building coq-libvalidsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-libvalidsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam install -y -v -j ${NJOBS} coq-libvalidsdp
    opam config list; opam repo list; opam list
    : done" coq-libvalidsdp
- echo -en 'travis_fold:end:coq-libvalidsdp\\r'
- echo -e "${ANSI_YELLOW}Building deps-coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:deps-coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    cd /home/coq/${CONTRIB_NAME}
    : Installing SDPA
    ./install_sdpa_on_debian_10.sh  # implies "sudo apt-get update -y -q"
    sdpa --version
    : Installing APT deps from OPAM
    # sudo apt-get update -y -q  # already done above
    travis_retry opam depext -i -y conf-gmp.1 conf-csdp.1 conf-sdpa.1
    sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # optional
    opam install -y -v -j ${NJOBS} coq-validsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-validsdp
- echo -en 'travis_fold:end:deps-coq-validsdp\\r'
- echo -e "${ANSI_YELLOW}Building coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam install -y -v -j ${NJOBS} coq-validsdp
    opam config list; opam repo list; opam list
    : done" coq-validsdp
- echo -en 'travis_fold:end:coq-validsdp\\r'

after_script:
- docker stop COQ
