os: linux
dist: bionic
language: shell

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="validsdp"
  jobs:
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.8.0-coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.10"
  - COQ_IMAGE="mathcomp/mathcomp:1.9.0-coq-8.11"
  - COQ_IMAGE="mathcomp/mathcomp:1.10.0-coq-8.7"
  - COQ_IMAGE="mathcomp/mathcomp:1.10.0-coq-8.8"
  - COQ_IMAGE="mathcomp/mathcomp:1.10.0-coq-8.9"
  - COQ_IMAGE="mathcomp/mathcomp:1.10.0-coq-8.10"
  - COQ_IMAGE="mathcomp/mathcomp:1.10.0-coq-8.11"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  # alternative to -v for Flocq's very large files Pff*:
  # travis_wait, to get a 20 mn timeout instead of 10 mn
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    : Updating OPAM cache
    opam update -y
    : Installing OPAM deps
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    opam pin add -n -y -k path coq-libvalidsdp .
    opam pin add -n -y -k path coq-validsdp .
    opam remove -y coq-mathcomp-character  # Check coq-mathcomp-field is enough
    opam install -y -v -j ${NJOBS} coq-libvalidsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-libvalidsdp

script:
- set -e
- echo -e "${ANSI_YELLOW}Building coq-libvalidsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-libvalidsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam install -y -v -j ${NJOBS} coq-libvalidsdp
    opam config list; opam repo list; opam list
    : done" coq-libvalidsdp
- echo -en 'travis_fold:end:coq-libvalidsdp\\r'
- echo -e "${ANSI_YELLOW}Building deps-coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:deps-coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    cd /home/coq/${CONTRIB_NAME}
    : Installing SDPA
    ./install_sdpa_on_debian_10.sh  # implies 'sudo apt-get update -y -q'
    sdpa --version
    : Installing APT deps from OPAM
    # sudo apt-get update -y -q  # already done above
    travis_retry opam depext -i -y conf-gmp.1 conf-csdp.1 conf-sdpa.1
    sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # optional
    opam install -y -v -j ${NJOBS} coq-validsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-validsdp
- echo -en 'travis_fold:end:deps-coq-validsdp\\r'
- echo -e "${ANSI_YELLOW}Building coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam install -y -v -j ${NJOBS} coq-validsdp
    opam config list; opam repo list; opam list
    : done" coq-validsdp
- echo -en 'travis_fold:end:coq-validsdp\\r'
- set +e

after_script:
- docker stop COQ
