dist: bionic
language: minimal

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="validsdp"
  - COQ_INTERVAL_URL="https://gitlab.inria.fr/coqinterval/interval.git"
  - COQ_INTERVAL_BRANCH="master-coq-master"
  matrix:
  - COQ_IMAGE="coqorg/coq:8.11"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    : Updating OPAM cache
    opam update -y
    : Installing OPAM deps
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    : Installing SDPA
    ./install_sdpa_on_debian_10.sh  # implies 'sudo apt-get update -y -q'
    sdpa --version
    : Installing APT deps from OPAM
    # sudo apt-get update -y -q  # already done above
    travis_retry opam depext -i -y conf-gmp.1 conf-csdp.1 conf-sdpa.1
    sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # optional
    opam pin add -n -y -k path coq-libvalidsdp .
    opam pin add -n -y -k path coq-validsdp .
    # opam remove -y coq-mathcomp-character  # Check coq-mathcomp-field is enough
    opam config list; opam repo list; opam list
    opam install -y -v -j ${NJOBS} conf-autoconf
    opam install -y -v -j ${NJOBS} --ignore-constraints-on=coq coq-flocq coq-mathcomp-ssreflect.1.9.0 coq-coquelicot.3.0.3
    # Install coq-interval
    git clone ${COQ_INTERVAL_URL}
    cd interval
    git checkout ${COQ_INTERVAL_BRANCH}
    ./autogen.sh
    ./configure
    ./remake -j${NJOBS}
    ./remake install
    opam install -y --fake --ignore-constraints-on=coq coq-interval.3.4.1
    cd ..
    opam install -y -v -j ${NJOBS} --ignore-constraints-on=coq coq-libvalidsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-libvalidsdp

script:
- set -e
- echo -e "${ANSI_YELLOW}Building coq-libvalidsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-libvalidsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    opam install -y -v -j ${NJOBS} --ignore-constraints-on=coq coq-libvalidsdp
    opam config list; opam repo list; opam list
    : done" coq-libvalidsdp
- echo -en 'travis_fold:end:coq-libvalidsdp\\r'
- echo -e "${ANSI_YELLOW}Building deps-coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:deps-coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    cd /home/coq/${CONTRIB_NAME}
    opam pin add -n -y -k git coq-paramcoq.1.1.2+coq8.11 "git+https://github.com/coq-community/paramcoq#v8.11"
    opam install -y -v -j ${NJOBS} --ignore-constraints-on="coq,coq-bignums" coq-validsdp --deps-only
    opam config list; opam repo list; opam list
    : done" deps-coq-validsdp
- echo -en 'travis_fold:end:deps-coq-validsdp\\r'
- echo -e "${ANSI_YELLOW}Building coq-validsdp...${ANSI_RESET}" && echo -en 'travis_fold:start:coq-validsdp\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    VERBOSE=1 opam install -y -v -j ${NJOBS} --ignore-constraints-on="coq,coq-bignums" coq-validsdp
    opam config list; opam repo list; opam list
    : done" coq-validsdp
- echo -en 'travis_fold:end:coq-validsdp\\r'
- set +e

after_script:
- docker stop COQ
