sudo: required
dist: trusty
language: coq
cache:
  apt: true
install:
- sudo add-apt-repository --yes ppa:avsm/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y opam
- opam init -y
- eval $(opam config env)
- opam config var root
- opam remote add coq-extra-dev https://coq.inria.fr/opam/extra-dev
- opam remote add coq-core-dev  https://coq.inria.fr/opam/core-dev
- opam remote add coq-released  https://coq.inria.fr/opam/released
- opam pin add -y -v coq 8.6
- opam list
script:
- opam pin add -y -vvv .