name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - mathcomp/mathcomp:2.2.0-coq-8.19
          - mathcomp/mathcomp:2.1.0-coq-8.18
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: 'coq-validsdp.opam'
        custom_image: ${{ matrix.image }}
        custom_script: |
          startGroup Print opam config
            opam config list; opam repo list; opam list
            echo NJOBS=${NJOBS}
          endGroup
          startGroup Update APT cache
            sudo apt-get update -y -q
          endGroup
          startGroup Update opam cache
            opam update -y
          endGroup
          startGroup Build coq-libvalidsdp dependencies
            opam pin add -n -y -k path coq-libvalidsdp .
            opam pin add -n -y -k path coq-validsdp .
            opam remove -y coq-mathcomp-character # coq-mathcomp-field is enough
            opam install -y -j ${NJOBS} coq-libvalidsdp --deps-only
            opam list
          endGroup
          startGroup Build coq-libvalidsdp
            opam install -y -v -j ${NJOBS} coq-libvalidsdp
            opam list
          endGroup
          startGroup Build coq-validsdp dependencies
            opam install --confirm-level=unsafe-yes -j ${NJOBS} coq-validsdp --deps-only
            opam list
          endGroup
          startGroup Build coq-validsdp
            opam install -y -v -j ${NJOBS} -t coq-validsdp
            opam list
          endGroup
          startGroup Uninstallation test
            opam remove -y coq-validsdp
            opam remove -y coq-libvalidsdp
            sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* # optional
          endGroup

# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
